#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 13 06:23:43 2018

@author: bill
"""

#from Tkinter import *
import tkinter as tk

class MyDialog:

    def __init__(self, parent):

        top = self.top = tk.Toplevel(parent)

        tk.Label(top, text="Value").pack()

        self.e = tk.Entry(top)
        self.e.pack(padx=5)

        b = tk.Button(top, text="OK", command=self.ok)
        b.pack(pady=5)

    def ok(self):

      #  print("value is", self.e.get())
        
        self.value = self.e.get()

        self.top.destroy()

if __name__ == "__main__":
    root = tk.Tk()
    tk.Button(root, text="Hello!").pack()
    root.update()
    
    for i in range(2):
        d = MyDialog(root)
        root.withdraw()
        root.wait_window(d.top)
        print(d.value)